### ISSUE TITLE
Create a website for the book

### ISSUE THREAD

**Issue by galgalesh** [0x20/hackerspace-blueprint#27]
It would be really useful to have a single-page website for this book. We could easily create a website in this repository by adding a github pages website in a separate branch.

# What should be on the website

* A short summary of the book (you can get it from here: https://www.amazon.com/Hackerspace-Blueprint-Empowering-people-awesome-ebook/dp/B07PP53RTR/)
* The cover art
* A URL to the latest PDF and EPUB versions of the book
* A URL to the amazon version
* A link to this github repository and a "fork me" message
* A link to hackerspace gent

**Comment by galgalesh** [comment]
Fixed: https://hackerspace.design/

**Comment by ZZEPPOSS** [comment]
Super work! Yay!
Tnx!
=;\ 

Hey Merlijn. Zou graag es afspreken —zodra dat past..— wil je graag (ontmoeten en) introduceren tot goeie vriend phychiater - filosoof - vrijdenker - old fart - ... die zeer erg diep thuis is in integratieve evolutie stuff... enzo...

En in gent woont.

Heb jouw blueprint aan hem voorgelegd... superenthousiast — kan m haast niet meer houden🤣.. 

Btw. Ben zelf redelijk goed thuis in C3 bende enzo of course..

Till soon?
Grtz!
=;\

**Comment by galgalesh** [comment]
Thanks! Ik ben benieuwd! Stuur mij gerust een email. merlijn.sebrechts AT gmail PUNT com
